name: Build and Push Readiness Probe Image

on:
  workflow_dispatch: # 允许手动触发此工作流
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # 镜像名称已更新，更通用
  IMAGE_NAME: ${{ github.repository }}/readiness-probe # 例如: your-org/your-repo/readiness-probe

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 需要写入权限才能推送到 GitHub Packages

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            zxavier/readiness-probe:latest
            ghcr.io/zhangxavier/readiness-probe:latest
            zxavier/readiness-probe:v0.0.1
            ghcr.io/zhangxavier/readiness-probe:v0.0.1
      -
         name: Update Hub description
         uses: peter-evans/dockerhub-description@v4
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           repository: zxavier/caddy
